application_port: 8080

sources:
  - endpoint: https://this-is-something.u.staging.voltageapp.io:10009
    macaroon: /Users/litch/code/lightning-projects/lndbalancer/mn-admin.macaroon
    cert: /Users/litch/code/lightning-projects/lndbalancer/nonsense.cert
